name = "VFitApproximation"
uuid = "f5054533-68e0-41c2-adcd-65cbda65cc54"
authors = ["Shubhang Goswami <sgoswam3@illinois.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
